from enum import Enum

from pydantic import BaseModel


class Categories(Enum):
    Business = "Бизнес"
    Appliances = "Бытовая техника"
    FoodDrink = "Еда и напитки"
    Animals = "Животные"
    Stationery = "Канцелярские"
    Goods = "товары"
    BeautyHealth = "Красота и здоровье"
    RealEstate = "Недвижимость"
    Education = "Образование"
    ClothingShoesAccessories = "Одежда, обувь и аксессуары"
    HolidaysTravel = "Отдых и путешествия"
    GiftsFlowers = "Подарки и цветы"
    Job = "Работа"
    EntertainmentLeisure = "Развлечения и досуг"
    AgriculturalEquipmentMachinery = "Сельскохозяйственное оборудование и техника"
    FamilyChildren = "Семья и дети"
    Sport = "Спорт"
    ConstructionArrangementRepair = "Строительство, обустройство и ремонт"
    Telecom = "Телеком"
    Transport = "Транспорт"
    Finance = "Финансы"
    Electronics = "Электроника"


class Themes(Enum):
    AccountingServices = "Бухгалтерские услуги"
    FreightTransportServices = "Грузоперевозки и транспортные услуги"
    WebsiteCreationPromotion = "Создание и продвижение сайтов"
    LegalServices = "Юридические услуи"
    Appliances = "Бытовая техника"
    WaterDelivery = "Доставка воды"
    Delivery = "Доставка готовых блюд и продуктов"
    Cooking = "Кулинария"
    Pets = "Домашние животные"
    Stationery = "Канцелярские товары"
    HealthyEating = "Здоровое питание"
    Medicine = "Медицина"
    PerfumesCosmetics = "Парфюмерия и косметика"
    BuyingRenting = "Покупка и аренда"
    AdditionalEducationCourses = "Дополнительное образование и курсы"
    SchoolUniversity = "Школа и вуз"
    ClothesShoes = "Одежда и обувь"
    Tickets = "Билеты"
    ForeignTourism = "Зарубежный туризм"
    CarRental = "Прокат автомобилей"
    RussianTourism = "Российский туризм"
    GiftsFlowers = "Подарки и цветы"
    Job = "Работа"
    Games = "Игры"
    Movie = "Кино"
    Books = "Книги"
    Music = "Музыка"
    Hunting = "Охота"
    Restaurants = "Рестораны"
    Fishing = "Рыбалка"
    Dancing = "Танцы"
    Theaters = "Театры"
    Television = "Телевидение"
    AgriculturalEquipmentMachinery = "Сельскохозяйственное оборудование и техника"
    PregnancyChildbirth = "Беременность и роды"
    Wedding = "Свадьба"
    GoodsChildren = "Товары для детей"
    Sport = "Спорт"
    InteriorDesign = "Дизайн интерьера"
    Furniture = "Мебель"
    Repair = "Ремонт"
    HouseholdProducts = "Товары для дома"
    InternetAccessMobileCommunications = "Доступ в интернет и мобильня связь"
    Auto = "Авто"
    Moto = "Мото"
    BanksLoans = "Банки и кредиты"
    Investments = "Инвестиции"
    Forex = "Форекс"
    ComputerTechnology = "Компьютерная техника"
    PrintersMFPs = "Принтеры и МФУ"
    SmartphonesGadgets = "Смартфоны и гаджеты"
    PhotoVideoAudioEquipment = "Фото, видео и аудиотехника"


class CategoryResponse(BaseModel):
    category: Categories | None = None
    theme: Themes | None = None
